theme: jekyll-theme-minimal
title: [Ben Wireman]
description: [
![Image](./assets/me.jpg)   
Ben Wireman Software Engineer at [Censys, inc](https://censys.io)   
BS Computer Science   
University of Michigan
]