name: Check Resume

on:
  schedule:
  - cron: "0 9 * * *"
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install gdown
    - name: download
      run: ./scripts/dl-resume.sh
    - name: check
      run: sha256sum -c ben_wireman_resume.pdf.sha256
    - uses: jayqi/failed-build-issue-action@v1
      if: failure()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
